# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4de7bc979e355b5ecc46c8d0051cdd4f7016a9f70ef8b71a03898b4a7088da7a3d59847493e5cb1fe66fbd0bad41dab14323a9ddc02f985c36da92e144ae8b33

test:
  secret_key_base: 046b0d114359c0a344c0f6d92b44f612b9f276a6f4f71874ecfa1ac83a363360046f589a7182741b5f7a77e6f4973ea516d9e5e84a38a574ae7ee5a2021220e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
